alter table SALES_ORDER_LINE add constraint FK_SALES_ORDER_LINE_PRODUCT_ID foreign key (PRODUCT_ID) references SALES_PRODUCT(ID);
alter table SALES_ORDER_LINE add constraint FK_SALES_ORDER_LINE_ORDER_ID foreign key (ORDER_ID) references SALES_ORDER(ID);
create index IDX_SALES_ORDER_LINE_ORDER on SALES_ORDER_LINE (ORDER_ID);
create index IDX_SALES_ORDER_LINE_PRODUCT on SALES_ORDER_LINE (PRODUCT_ID);
